name: example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cupertino_icons:
  firebase_auth:
  firebase_core:
  flutter:
    sdk: flutter
  flutter_riverpod:
  gap:
  go_router:
  mono_kit:
  url_launcher:

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  go_router_builder:
  pedantic_mono:

dependency_overrides:
  mono_kit: '>=0.26.0-0'

flutter:
  uses-material-design: true
